add docker build config

diff --git a/.github/workflows/ci_setup.yml b/.github/workflows/ci_setup.yml
--- a/.github/workflows/ci_setup.yml
+++ b/.github/workflows/ci_setup.yml
@@ -2,7 +2,7 @@ name: CI workflow to build AI app
 
 on:
   push:
-    branches:
+    branches: 
       - feature-1
 
 jobs:
@@ -156,4 +156,39 @@ jobs:
           npm install -g @sonar/scan
           sonar-scanner -Dsonar.organization=apurva14a -Dsonar.projectKey=Apurva14A_AI-quotes-generator  -Dsonar.sources=src -Dsonar.token=${{ env.SONAR_TOKEN }} 
         
-  
+  build-docker-image:
+    runs-on: [ubuntu-latest]
+    needs: Code_coverage
+    environment: development
+
+    env:
+      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
+    
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4.2.2
+        with:
+          fetch-depth: 0
+
+      - name: Docker Login
+        id: docker-login
+        uses: docker/login-action@v2.0.0
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+
+      - name: Build Docker image
+        id: build-image
+        run: |
+          if {{ steps.docker-login.outputs.login == 'success' }}; then
+            echo "Docker login successful"
+            docker build -t aapurva/sde-project-2025:dev-0.1 .
+            docker push aapurva/sde-project-2025:dev-0.1
+          else
+            echo "Docker login failed"
+            exit 1
+          fi
+        
